using System;
using SqlFu;

namespace TemperatureEstimator.Entities
{
    [Table("DateTemperature", AutoGenerated = true, PrimaryKey = "Id")]
    public class DateTemperature : IDateValue
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public double Temperature { get; set; }
        public string Airport { get; set; }

        public double Value
        {
            get { return Temperature; }
            set { Temperature = value; }
        }
    }
}